### ISSUE TITLE
No effect on AWS Lightsail VPS

### ISSUE THREAD

**Issue by RaitoBezarius** [nix-community/nixos-anywhere#139]
**Describe the bug**

Try to nixos-anywhere an Ubuntu AWS Lightsail VPS and... it just reboot in Ubuntu :-[.

**To Reproduce**

1. Create an AWS Lightsail VPS (those are free for 3 months for new accounts I guess?)
2. Try to kexec it via nixos-anywhere.

**Expected behavior**

NixOS!!

**System information**

Ubuntu 22.04 LTS, 2GB of RAM, Xen domU.

**Additional context**

**Comment by Mic92** [comment]
Did you went out of memory maybe? 2GB might be borderline.

**Comment by RaitoBezarius** [comment]
> Did you went out of memory maybe? 2GB might be borderline.

Good point.

**Comment by RaitoBezarius** [comment]
Will retry with --debug on 2GB and 4GB to rule out the RAM problem.

**Comment by JimZAH** [comment]
@RaitoBezarius Did you manage to get this working?

**Comment by Mic92** [comment]
We also now use the kexec syscall if available, which might help.

**Comment by Mic92** [comment]
Please retry. It should also work with 2G these days.
