### ISSUE TITLE
Pass options to Nix?

### ISSUE THREAD

**Issue by MrFoxPro** [nix-community/nixos-anywhere#165]
**Is your feature request related to a problem? Please describe.**
I want to deploy impure system and seems like it's impossible right now.

**Describe the solution you'd like**
Pass arguments to Nix as `deploy-rs` does like `nixos-anywhere --flake .#nixos root@address -- --impure`

**Comment by MrFoxPro** [comment]
> We can allow `--option option value` and pass this to all nix related commands.

how do I pass `--impure` then?

**Comment by Mic92** [comment]
It's called `pure-eval` as a setting.

**Comment by I-Want-ToBelieve** [comment]
```
nix-server-ng --port 8080
nix run github:nix-community/nixos-anywhere -- --flake '.#xxx' --option pure-eval false --option substituters http://192.168.0.121:8080 --print-build-logs --debug nixos@192.168.0.185 
```
