### ISSUE TITLE
Signature error when following the how-to guide for installing on a machine without an operating system

### ISSUE THREAD

**Issue by kilianar** [nix-community/nixos-anywhere#173]
**Description of the bug**

While attempting to install NixOS on a bare metal x86_64 machine using nixos-anywhere, I encountered an issue. I followed the [guide on installing on a system without an operating system](https://numtide.github.io/nixos-anywhere/howtos.html#installing-on-a-machine-with-no-operating-system). First, I downloaded the latest Gnome ISO image from https://nixos.org, then I booted it on the target machine, and finally, I executed the following command on another machine running NixOS:

```shell
nix run github:numtide/nixos-anywhere -- --flake .#my-nixos-config nixos@192.168.1.100
```

However, this resulted in an error related to signatures:
```
error: cannot add path '/nix/store/lkdb5zm8s6zpgxmpn5map96072v08g1r-disko' because it lacks a signature by a trusted key
```

Interestingly, when I used the root user account:

```shell
nix run github:numtide/nixos-anywhere -- --flake .#my-nixos-config root@192.168.1.100
```

everything worked as expected and the installation succeeded. Hence, it seems to be an issue with permissions on the target machine. The root user account appears to be able to add store paths without a trusted signature, while the nixos user account cannot.

**Expected behavior**

Following the steps in the how-to guide should not result in an error.

**Additional information**

Output when run with `--debug` option:
```
### Formatting the hard drive with disko ###
+ nix_copy --to ssh://nixos@192.168.1.100 /nix/store/lkdb5zm8s6zpgxmpn5map96072v08g1r-disko
+ NIX_SSHOPTS='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/tmp.0DKmLmqnBD/nixos-anywhere '
+ nix copy --extra-experimental-features 'nix-command flakes' --no-write-lock-file -L --substitute-on-destination --to ssh://nixos@192.168.1.100 /nix/store/lkdb5zm8s6zpgxmpn5map96072v08g1r-disko
error: cannot add the path '/nix/store/lkdb5zm8s6zpgxmpn5map96072v08g1r-disko' because it lacks a signature by a trusted key
error: unexpected end-of-file
```

**Comment by Mic92** [comment]
Looks like the normal nixos user is not a "trusted" user on this installation target. I think I may have only tested this for root back than. While using root would be the alternative I don't think we allow root password login. So maybe it's better to fix this the installation media.

**Comment by kilianar** [comment]
Thank you for addressing the issue. At least, when I tried it, I was able to log in as root via SSH using passwords with the official ISO image.
