### ISSUE TITLE
bash: line 10: syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by niki-on-github** [nix-community/nixos-anywhere#174]
**Describe the bug**

nixos-anywhere show the following output:

```
Installation finished. No error reported.
installation finished!
-bash: line 10: syntax error near unexpected token `fi'
```

**To Reproduce**

Use nixos-anywhere to deploy an setup.

**Expected behavior**

No syntax error in nixos-anywhere

**Additional context**

The error messages was introduced in #160. 

Apply the patch below resolve the syntax error and nixos-anywhere works again as desired.

```patch
--- a/src/nixos-anywhere.sh
+++ b/src/nixos-anywhere.sh
@@ -443,9 +443,7 @@ export PATH=\$PATH:/run/current-system/sw/bin
 mkdir -p /mnt/tmp
 chmod 777 /mnt/tmp
 nixos-install --no-root-passwd --no-channel-copy --system "$nixos_system"
-if command -v zpool >/dev/null; then
-  zpool export -a || : # we always want to export the zfs pools so people can boot from it without force import
-fi
+! command -v zpool >/dev/null || zpool export -a || : # we always want to export the zfs pools so people can boot from it without force import
 # We will reboot in background so we can cleanly finish the script before the hosts go down.
 # This makes integration into scripts easier
 nohup bash -c '${maybe_reboot}' >/dev/null &
```

**Comment by Mic92** [comment]
I can execute this here without issues in bash. What shell was used in your case?

**Comment by niki-on-github** [comment]
> What login shell was used in your case?

I boot the nixos x86_64 minimal iso on the target. The login shell is `bash`. I also tried different shells (zsh and bash) on host where i call `nix --extra-experimental-features nix-command --extra-experimental-features flakes run github:numtide/nixos-anywhere -- --extra-files "/an/additional/dir" --flake '.#test' nixos@$IP`. I always get the syntax error described above.

**Comment by phaer** [comment]
Could it be that the single `:`, as the last non-comment token before ´fi´ throws it of rails?
I've seen `|| :` before in bash, but I am still not entirely whether there's a semantic difference compared to `|| true`? The latter also seems more readable imo.

**Comment by niki-on-github** [comment]
Ok could now narrow down the problem. I use the following config option in my system flake config:

```nix
boot.loader.grub.extraPrepareConfig = ''
  ${pkgs.cryptsetup}/bin/cryptsetup luksOpen --test-passphrase /dev/disk/by-partlabel/luks_system --key-file /boot/keys/disk.key || ${pkgs.cryptsetup}/bin/cryptsetup luksAddKey /dev/disk/by-partlabel/luks_system /boot/keys/disk.key
  chmod 000 /boot/keys/disk.key
'';
```

without this config option nixos-anywhere works without modification and has no syntax error.

But why does the config parameter corrupt the nixos-anywhere calls?

When i add the lines:
```bash
echo a
echo b
echo c
```

after the `nixos-install --no-root-passwd --no-channel-copy --system "$nixos_system"` in `
src/nixos-anywhere.sh`. Then i only see the following output (when using the `boot.loader.grub.extraPrepareConfig` config option):

```
Installing for x86_64-efi platform.
Installation finished. No error reported.
installation finished!
b
c
```

=> nixos-anywhere jumps over the next instruction when i use `boot.loader.grub.extraPrepareConfig` config option. Therefore `if command -v zpool >/dev/null; then` is never executed in this case. And we get the syntax error `bash: line 10: syntax error near unexpected token 'fi'`.

**Comment by Mic92** [comment]
I think the error was in nixos-install not nixos-anywhere.
