### ISSUE TITLE
diskoScript

### ISSUE THREAD

**Issue by jzbor** [nix-community/nixos-anywhere#226]
Hi,
I am trying to install a system using `nixos-anywhere` v1.0.0 and `disko` v1.0.0. I get the following error:
```console
$ nix run github:numtide/nixos-anywhere -- --flake .#cs3-emmy-1 cs3-emmy-1        
error: flake 'path:/home/jzbor/Programming/Nix/nixos-emmy' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."cs3-emmy-1".config.system.build.diskoScript', 'legacyPackages.x86_64-linux.nixosConfigurations."cs3-emmy-1".config.system.build.diskoScript' or 'nixosConfigurations."cs3-emmy-1".config.system.build.diskoScript'
```
Are the two versions of `nixos-anywhere` and `disko` compatible. If not are there stable versions that are compatible?

**Comment by Lassulus** [comment]
ah disko v1.0.0 is a bit outdated. I would suggest using the most recent one

**Comment by Lassulus** [comment]
I just tagged v1.1.0, hopefully that is good enough :)

**Comment by jzbor** [comment]
Ok thank you, I'll give it a try
