### ISSUE TITLE
Missing dm-raid module

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixos-anywhere#249]
## Symptom
When disko is running, it fails like that:
```
+ vgcreate pool /dev/nvme0n1p3 /dev/nvme1n1p3
  Volume group "pool" successfully created
+ lvcreate --yes -L 100G -n root --type=raid0 pool
  raid0: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
+ rm -rf /tmp/tmp.I0JMbBPuNI
```
## Workaround

If that happens, ssh into the kexeced environment and run `modprobe dm-raid`. Then re-run nixos-anywhere.

## Context

Here is how the disko config looks like: https://gist.github.com/zimbatm/0bcc224d2c22236fec6e34dff05b6123

**Comment by Lassulus** [comment]
Probably something to fiz in nixos-images?
