### ISSUE TITLE
how-to link in README broken

### ISSUE THREAD

**Issue by sedlund** [nix-community/nixos-anywhere#259]
From breakup of how-tos daea29d1e1217832b8a64bec8214e463ab8f3160

how-to link in README:

https://github.com/nix-community/nixos-anywhere/blob/73a6d3fef4c5b4ab9e4ac868f468ec8f9436afa7/README.md?plain=1#L57

should be `./docs/howtos/no-os.md`

and

https://github.com/nix-community/nixos-anywhere/blob/73a6d3fef4c5b4ab9e4ac868f468ec8f9436afa7/README.md?plain=1#L79

`./docs/howtos/custom-kexec.md`

and

https://github.com/nix-community/nixos-anywhere/blob/73a6d3fef4c5b4ab9e4ac868f468ec8f9436afa7/README.md?plain=1#L90

should be:

`./docs/howtos/INDEX.md`

**Comment by Mic92** [comment]
fixed in https://github.com/nix-community/nixos-anywhere/commit/90894fe52998513229f268249ffedce90169431f
