### ISSUE TITLE
rsync command not found with 23.11 nixos image

### ISSUE THREAD

**Issue by Tommixe** [nix-community/nixos-anywhere#260]
nixos-anywhere fails at copy extra file step using as installation target a machine booted with nixos 23.11 minimal iso image: 
https://channels.nixos.org/nixos-23.11/latest-nixos-minimal-x86_64-linux.iso

nixos-anywhere command:
nix run github:numtide/nixos-anywhere -- --extra-files "$temp" --flake .#server02 root@$192.168.178.191

This is the error:

```nix
+ echo '### Copying extra files ###'
### Copying extra files ###
+ rsync -rlpv -FF -e 'ssh -i "/tmp/tmp.eYUCcg96wX"/nixos-anywhere -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ' /tmp/tmp.Ol4VOcuUb6/ root@192.168.178.191:/mnt/
Warning: Permanently added '192.168.178.191' (ED25519) to the list of known hosts.
bash: line 1: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.2.7]
+ rm -rf /tmp/tmp.eYUCcg96wX
``` 
Using the 23.05 image installation works without any issue.

**Comment by Mic92** [comment]
We should probably start making our own ISOs that have all needed tools.

**Comment by Ramblurr** [comment]
Is there a workaround?

**Comment by Mic92** [comment]
Another work around is building your own installer. nixos-generators works well for that.

**Comment by Lassulus** [comment]
maybe we can do a fallback with nix-shell?

**Comment by 0x4A6F** [comment]
Editing `/etc/nixos/configuration.nix` and adding `rsync` to `systemPackages` with a `nixos-rebuild test` also works on current minimal iso.
```nix
  environment.systemPackages = with pkgs; [
    rsync
  ];
```

**Comment by Lassulus** [comment]
hmm, but thats a lot of hassle. Maybe we should just port the rsync code to scp?

**Comment by Mic92** [comment]
We also create a new nixos-anywhere optimized installer image that has rsync installed and enables sshd by default: https://github.com/nix-community/nixos-images?tab=readme-ov-file#iso-installer-images

**Comment by uPaymeiFixit** [comment]
> We also create a new nixos-anywhere optimized installer image that has rsync installed and enables sshd by default: [nix-community/nixos-images#iso-installer-images](https://github.com/nix-community/nixos-images?tab=readme-ov-file#iso-installer-images)

I saw this a few days ago and could not for the life of me figure out where the ISOs are actually hosted. I'm new to nix and figure I must misunderstand how it works.

**Comment by Prince213** [comment]
To anyone who is looking at this, #316 (or #325) has been merged and it solves the problem.
