### ISSUE TITLE
Kexec arm issue on hetzner cloud

### ISSUE THREAD

**Issue by spolakh** [nix-community/nixos-anywhere#263]
Just creating a github issue to track what is being discussed on Matrix.

Trying to run nixos-anywhere against a hetzner cloud arm instance gets to kexec but isnt able to successfully come up afterwords and is unreachable until rebooted from console (where it boots back into original system).

Original Matrix message from nrv:
https://matrix.to/#/!NfgJ0qKGIQeNakJs:thalheim.io/$pO8CfIT0ubjIvT8kQYUUX_Owgf115LtZQ7BXa3GCir0?via=thalheim.io&via=matrix.org&via=beeper.com

**Comment by spolakh** [comment]
Update from @Mic92 on matrix:

> So I figured out that if you use Fedora and Debian instead of ubuntu than kexec works fine.
> For ubuntu it works if you kexec is run without --kexec-syscall-auto, this currently is hardcoded in the kexec installer script

Will close this then

**Comment by Mic92** [comment]
This one also makes it work now with older kernel. Tested on hetzner cloud (arm): https://github.com/nix-community/nixos-images/pull/155
