### ISSUE TITLE
kexec_file_load failed: Key was rejected by service (CentOS 7 + proxmox)

### ISSUE THREAD

**Issue by justyns** [nix-community/nixos-anywhere#264]
I'm trying to run nixos-anywhere against a CentOS 7 vm on Proxmox and getting this error:

```
> nix run github:nix-community/nixos-anywhere -- --flake ~/dev/homelab-nixos/#proxmox-one-disk --disk-encryption-keys /tmp/remote.key /tmp/remote.key justyns@192.168.5.245
...
+ gzip -9
21 blocks
+ /root/kexec/kexec/kexec --load /root/kexec/kexec/bzImage --kexec-syscall-auto --initrd=/root/kexec/kexec/initrd --no-checks --command-line 'init=/nix/store/cbsbl629dja6cxr3saw0
kj55khjwsgyv-nixos-system-nixos-23.11pre-git/init console=tty0 console=ttyS0,115200 loglevel=4'
kexec_file_load failed: Key was rejected by service
kexec failed, dumping dmesg
```

<details><summary>dmesg output: </summary>
<pre>
+ dmesg
[    1.274655] device-mapper: uevent: version 1.0.3
[    1.274776] device-mapper: ioctl: 4.37.1-ioctl (2018-04-03) initialised: dm-devel@redhat.com
[    1.304090] usb 1-1: new full-speed USB device number 2 using uhci_hcd
[    1.402534] FDC 0 is a S82078B
[    1.445501] libata version 3.00 loaded.
[    1.469936] usb 1-1: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
[    1.469940] usb 1-1: New USB device strings: Mfr=1, Product=3, SerialNumber=10
[    1.469943] usb 1-1: Product: QEMU USB Tablet
[    1.469945] usb 1-1: Manufacturer: QEMU
[    1.469947] usb 1-1: SerialNumber: 28754-0000:00:01.2-1
[    1.478388] input: QEMU QEMU USB Tablet as /devices/pci0000:00/0000:00:01.2/usb1/1-1/1-1:1.0/input/input4
[    1.478513] hid-generic 0003:0627:0001.0001: input,hidraw0: USB HID v0.01 Mouse [QEMU QEMU USB Tablet] on usb-0000:00:01.2-1/input0
[    1.520553] ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 10
[    1.522648] ata_piix 0000:00:01.1: version 2.13
[    1.526563] scsi host0: ata_piix
[    1.533016] scsi host1: ata_piix
[    1.533077] ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xe100 irq 14
[    1.533078] ata2: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xe108 irq 15
[    1.594440] ACPI: PCI Interrupt Link [LNKA] enabled at IRQ 10
[    1.659742] ACPI: PCI Interrupt Link [LNKB] enabled at IRQ 11
[    1.661517] [drm] Found bochs VGA, ID 0xb0c5.
[    1.661526] [drm] Framebuffer size 16384 kB @ 0xfd000000, mmio @ 0xfea50000.
[    1.661642] [TTM] Zone  kernel: Available graphics memory: 940812 kiB
[    1.661644] [TTM] Initializing pool allocator
[    1.661649] [TTM] Initializing DMA pool allocator
[    1.663668] [drm] Found EDID data blob.
[    1.667271] fbcon: bochsdrmfb (fb0) is primary device
[    1.678540] virtio-pci 0000:00:08.0: irq 24 for MSI/MSI-X
[    1.678581] virtio-pci 0000:00:08.0: irq 25 for MSI/MSI-X
[    1.683944] virtio-pci 0000:00:12.0: irq 26 for MSI/MSI-X
[    1.683974] virtio-pci 0000:00:12.0: irq 27 for MSI/MSI-X
[    1.684003] virtio-pci 0000:00:12.0: irq 28 for MSI/MSI-X
[    1.685361] Console: switching to colour frame buffer device 128x48
[    1.687025] bochs-drm 0000:00:02.0: fb0: bochsdrmfb frame buffer device
[    1.687447] virtio-pci 0000:00:05.0: irq 29 for MSI/MSI-X
[    1.687493] virtio-pci 0000:00:05.0: irq 30 for MSI/MSI-X
[    1.687522] virtio-pci 0000:00:05.0: irq 31 for MSI/MSI-X
[    1.687552] virtio-pci 0000:00:05.0: irq 32 for MSI/MSI-X
[    1.687581] virtio-pci 0000:00:05.0: irq 33 for MSI/MSI-X
[    1.688718] scsi host2: Virtio SCSI HBA
[    1.691274] [drm] Initialized bochs-drm 1.0.0 20130925 for 0000:00:02.0 on minor 0
[    1.691517] scsi 2:0:0:0: Direct-Access     QEMU     QEMU HARDDISK    2.5+ PQ: 0 ANSI: 5
[    1.699798] ata2.01: NODEV after polling detection
[    1.700086] ata1.01: NODEV after polling detection
[    1.700460] ata2.00: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[    1.701192] ata1.00: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[    1.701518] ata2.00: configured for MWDMA2
[    1.702653] ata1.00: configured for MWDMA2
[    1.703169] scsi: waiting for bus probes to complete ...
[    1.718640] random: fast init done
[    1.725095] scsi 0:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.5+ PQ: 0 ANSI: 5
[    1.729629] scsi 1:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.5+ PQ: 0 ANSI: 5
[    1.753396] sr 0:0:0:0: [sr0] scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[    1.753401] cdrom: Uniform CD-ROM driver Revision: 3.20
[    1.753743] sr 0:0:0:0: Attached scsi CD-ROM sr0
[    1.764777] sr 1:0:0:0: [sr1] scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[    1.765201] sr 1:0:0:0: Attached scsi CD-ROM sr1
[    1.770709] sd 2:0:0:0: Power-on or device reset occurred
[    1.771018] sd 2:0:0:0: [sda] 67108864 512-byte logical blocks: (34.3 GB/32.0 GiB)
[    1.771310] sd 2:0:0:0: [sda] Write Protect is off
[    1.771313] sd 2:0:0:0: [sda] Mode Sense: 63 00 00 08
[    1.771396] sd 2:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.773895]  sda: sda1 sda2
[    1.774808] sd 2:0:0:0: [sda] Attached SCSI disk
[    1.924990] tsc: Refined TSC clocksource calibration: 2199.985 MHz
[    2.178872] SGI XFS with ACLs, security attributes, no debug enabled
[    2.182889] XFS (dm-0): Mounting V5 Filesystem
[    2.251015] XFS (dm-0): Ending clean mount
[    2.539150] systemd-journald[99]: Received SIGTERM from PID 1 (systemd).
[    2.653898] SELinux:  Disabled at runtime.
[    2.653946] SELinux:  Unregistering netfilter hooks
[    2.695968] type=1404 audit(1702888666.187:2): selinux=0 auid=4294967295 ses=4294967295
[    2.717546] systemd[1]: RTC configured in localtime, applying delta of -360 minutes to system time.
[    2.755269] ip_tables: (C) 2000-2006 Netfilter Core Team
[    2.755359] systemd[1]: Inserted module 'ip_tables'
[    3.255993] systemd-journald[517]: Received request to flush runtime journal from PID 1
[    3.274040] random: crng init done
[    3.420141] piix4_smbus 0000:00:01.3: SMBus Host Controller at 0x700, revision 0
[    3.459576] sd 2:0:0:0: Attached scsi generic sg0 type 0
[    3.459620] sr 0:0:0:0: Attached scsi generic sg1 type 5
[    3.459652] sr 1:0:0:0: Attached scsi generic sg2 type 5
[    3.461775] input: PC Speaker as /devices/platform/pcspkr/input/input5
[    3.491122] cryptd: max_cpu_qlen set to 1000
[    3.517496] AVX version of gcm_enc/dec engaged.
[    3.517500] AES CTR mode by8 optimization enabled
[    3.576414] alg: No test for __gcm-aes-aesni (__driver-gcm-aes-aesni)
[    3.576468] alg: No test for __generic-gcm-aes-aesni (__driver-generic-gcm-aes-aesni)
[    3.586571] Adding 3354620k swap on /dev/mapper/centos-swap.  Priority:-2 extents:1 across:3354620k FS
[    3.597206] XFS (sda1): Mounting V5 Filesystem
[    3.730549] EDAC sbridge: Seeking for: PCI ID 8086:0ea0
[    3.730555] EDAC sbridge:  Ver: 1.1.2
[    4.623330] XFS (sda1): Ending clean mount
[    4.713121] type=1305 audit(1702910268.204:3): audit_pid=661 old=0 auid=4294967295 ses=4294967295 res=1
[    5.846538] ip6_tables: (C) 2000-2006 Netfilter Core Team
[    5.903232] Ebtables v2.0 registered
[    5.933389] ip_set: protocol 7
[    6.283588] nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
[    6.284760] ISO 9660 Extensions: RRIP_1991A
[    6.421995] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    6.696352] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready

</pre>
</details> 

selinux was enabled but I disabled selinux and ran into the same error.  Running the kexec command with `-d` doesn't show anything else.  Is there something I could be missing in the vm itself?   I do have other vms with similar settings with nixos on them in the same cluster, using the default non-uefi bios.

**Comment by phaer** [comment]
>  I do have other vms with similar settings with nixos on them in the same cluster, using the default non-uefi bios.

You are positive that you use legacy boot and therefore no secure boot for this machine as well? Because while I am not certain, the error message seems to be similar to the one one would expect if secure boot was enabled. Could you check, i.e. by running

sudo mokutil --sb-state

?

**Comment by justyns** [comment]
I am fairly certain, but I'm also not super familiar with efi/secureboot to begin with.  When I was searching for the error, I saw some threads about secureboot/efi too.  

Here's the output of mokutil:

```
[root@nixoscentos7-01 ~]# mokutil --sb-state
EFI variables are not supported on this system
```

And the vm settings in proxmox:
<img width="678" alt="image" src="https://github.com/nix-community/nixos-anywhere/assets/215985/d0efb400-91e3-4d8e-84b9-d120fae07a91">

**Comment by Mic92** [comment]
I have the same issue on old arm64 ubuntu kernels on hetzner cloud.
In proxmox you are likely not having secure boot enabled.
The workaround in hetzner cloud was to use Fedora 38, which has a newer kernel.
It would also work to not use `--kexec-syscall-auto` but this is currently hardcoded in our kexec installer.

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/nixos-images/pull/155

**Comment by justyns** [comment]
Thanks!   It looks like that fix is working for me
