### ISSUE TITLE
no-os install requires root login

### ISSUE THREAD

**Issue by sedlund** [nix-community/nixos-anywhere#279]
I am installing NixOS with a booted installer CD this document mentions it can be done as nixos user that is present on the installer cd.

https://github.com/nix-community/nixos-anywhere/blob/4c94cecf3dd551adf1359fb06aa926330f44e5a6/docs/howtos/no-os.md?plain=1#L22

but I received these errors:

```
+ wipefs --all -f /dev/xvda1
wipefs: error: /dev/xvda1: probing initialization failed: Permission denied
+ wipefs --all -f /dev/xvda2
wipefs: error: /dev/xvda2: probing initialization failed: Permission denied
+ wipefs --all -f /dev/xvda3
wipefs: error: /dev/xvda3: probing initialization failed: Permission denied
++ zdb -l /dev/xvda
++ sed -nr 's/ +name: '\''(.*)'\''/\1/p'
+ zpool=
+ [[ -n '' ]]
+ unset zpool
++ lsblk /dev/xvda -l -p -o type,name
++ awk 'match($1,"raid.*") {print $2}'
+ md_dev=
+ [[ -n '' ]]
+ wipefs --all -f /dev/xvda
wipefs: error: /dev/xvda: probing initialization failed: Permission denied
+ dd if=/dev/zero of=/dev/xvda bs=440 count=1
dd: failed to open '/dev/xvda': Permission denied
++ mktemp -d
+ disko_devices_dir=/tmp/tmp.FR9K6lAylU
+ trap 'rm -rf "$disko_devices_dir"' EXIT
+ mkdir -p /tmp/tmp.FR9K6lAylU
+ device=/dev/xvda
+ imageSize=2G
+ name=disk1
+ type=disk
+ device=/dev/xvda
+ efiGptPartitionFirst=1
+ type=gpt
+ sgdisk --align-end --new=1:0:+1M --change-name=1:disk-disk1-space --typecode=1:EF02 /dev/xvda
Problem opening /dev/xvda for reading! Error is 13.
You must run this program as root or use sudo!
```

I'd be happy to update the no-os doc to reflect that root is required.  Or if you'd like to double check that sudo is being called in the appropriate places in the code.

Let me know

**Comment by ralpheichelberger** [comment]
I found this to be the case too. Works fine as long as root login on SSH is allowed including password auth is allowed or an entry in the authorized_users for the installing machine exists on the target host. All of that is not available on a Ubuntu Life-CD for example. With Nixos installer it's a peace of cake though.

**Comment by sedlund** [comment]
I wonder if this 

https://github.com/nix-community/nixos-anywhere/blob/31c945ed58a3accbf86b0cf82e5e49fa4db62407/src/nixos-anywhere.sh#L441

needs to be:

`ssh_ "${maybe_sudo}" "$disko_script"`

**Comment by ibizaman** [comment]
@sedlund not exactly. It should be something like this IMO

https://github.com/nix-community/nixos-anywhere/blob/31c945ed58a3accbf86b0cf82e5e49fa4db62407/src/nixos-anywhere.sh#L377-L381
