### ISSUE TITLE
Update a configuration

### ISSUE THREAD

**Issue by ralpheichelberger** [nix-community/nixos-anywhere#288]
After installing a host with nixos-anywhere there is no configuration.nix in the /etc/nixos.

Therefore one can not change the configuration or even update the system. It would be good to have those files on the newly installed system.

Is there a remote way to change and update?

**Comment by phaer** [comment]
> Is there a remote way to change and update?

How did you install the host? You should already have a flake that contains your configuration, so you could apply changes with all kinds of nixos deployment options, i.e.
`nixos-rebuild switch --target-host $target $flake#$target`.

**Comment by ralpheichelberger** [comment]
Yes, someone told me on the NixOS forum - thanks for replying though!

How about adding it to the docs? Not everyone who finds you awesome project is an Nix expert an need  guidance.
