### ISSUE TITLE
Running extra commands at the end

### ISSUE THREAD

**Issue by sweenu** [nix-community/nixos-anywhere#294]
My config allows me to ssh only to machines on my tailscale network. Therefore, after running `nixos-anywhere` on a new remote machine, I'm blocked out of it because I haven't had the opportunity to run `tailscale up` and log in.

It'd be useful to be able to pass an extra command to run at the end, and output the result.

**Comment by Lassulus** [comment]
hmm, thats a bit complicated, since nixos-anywhere doesn't manage the machine which you install with it.
So to run this command we would need to connect to the installed machine. But if that command needs to be run to reach that machine, how can we connect to it to run that command?

**Comment by sweenu** [comment]
Oh right, all the commands are run within the kexec right?
I think I found a solution to my problem: https://tailscale.com/kb/1085/auth-keys

We can close this I guess, doesn't seem doable.

**Comment by Lassulus** [comment]
yes all is run in the kexec, I guess you could generate a key locally and copy it with extra-files?

**Comment by sweenu** [comment]
The key is just a string I need to pass to the `tailscale up` command.
