### ISSUE TITLE
Target with no access to internet

### ISSUE THREAD

**Issue by Rider128** [nix-community/nixos-anywhere#296]
Hello,

I am writing to request a feature that would allow for offline installation of nixOS anywhere. Currently, the installation script attempts to download the kexec installer from the internet, which is problematic for systems without internet access.

Here is the error message I encountered during my attempt to install NixOS on an offline system:

```
### Gathering machine facts ###
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '192.168.100.129' (ED25519) to the list of known hosts.
sh: 11: [[: not found
sh: 12: [[: not found
### Switching system into kexec ###
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '192.168.100.129' (ED25519) to the list of known hosts.
Warning: Permanently added '192.168.100.129' (ED25519) to the list of known hosts.
--2024-03-28 09:24:41--  https://github.com/nix-community/nixos-images/releases/download/nixos-23.11/nixos-kexec-installer-noninteractive-x86_64-linux.tar.gz
Résolution de github.com (github.com)… échec : Échec temporaire dans la résolution du nom.
wget : impossible de résoudre l’adresse de l’hôte ‘github.com’

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Connection to 192.168.100.129 closed.
```

I propose that an option be added to the installation script to allow for the local download of the kexec file, which can then be transferred to the target system using scp or another file transfer method. This would greatly facilitate the installation of NixOS on systems without internet access.

Thank you for considering this request.

**Comment by phaer** [comment]
Hello,

> I propose that an option be added to the installation script to allow for the local download of the kexec file, which can then be transferred to the target system using scp or another file transfer method.

You can already scp a custom (or pre-downloaded) kexec image and pass the filename to nixos-anywheres `--kexec` argument.

**Comment by phaer** [comment]
Okay, just to make sure: You are asking about a flag that does the equivalent of:

```shell-session
curl -O https://github.com/nix-community/nixos-images/releases/download/nixos-23.11/nixos-kexec-installer-noninteractive-x86_64-linux.tar.gz
scp nixos-kexec-installer-noninteractive-x86_64-linux.tar.gz $target_host:
nixos-anywhere --kexec nixos-kexec-installer-noninteractive-x86_64-linux.tar.gz [...] $target_host
```

The installation should then work without network - except for the SSH connection you need for nixos-anywhere - anywhere. A

**Comment by Rider128** [comment]
That's what I was thinking 👍

**Comment by Mic92** [comment]
Targets without internet access is out-of-scope for nixos-anywhere. You can have a look at building your own installer that embeds disko-install. Documented here: https://github.com/nix-community/disko/blob/master/docs/disko-install.md#example-for-a-nixos-installer
