### ISSUE TITLE
Silent failure

### ISSUE THREAD

**Issue by ravloony** [nix-community/nixos-anywhere#321]
I'm trying to get a Hetzner root server set up using this tool.

I have a disko config, and am using https://github.com/nix-community/nixos-anywhere-examples as a starting point. I initially used https://github.com/LGUG2Z/nixos-hetzner-robot-starter with a pre-existing nixops config which I merged in, but moved to the simpler one with just the bare minimum: disk config and ssh key, intending to build on that basis if it worked.

Anyway, in both cases, the whole thing gets all the way to the `nix build --print-out-paths --no-link --extra-experimental-features 'nix-command flakes' --no-write-lock-file -L '.#nixosConfigurations."hetzner-robot".config.system.build.diskoScript'` step (as output by `--debug`) and then just stops. No errrors are output.

In the simple setup, my command line looks like this:

```sh
nix -v run github:nix-community/nixos-anywhere  -- --debug -L --flake '.#hetzner-robot' 'root@<IP>`
```

Where `IP` is the root server running a rescue system (which I can log in to as root), and `hetzner-robot` is this:

```nix
nixosConfigurations.hetzner-robot = nixpkgs.lib.nixosSystem {
   system = "x86_64-linux";
   modules = [
     disko.nixosModules.disko
     ./configuration.nix
   ];
};
```

Full debug output:

```
+ shift
+ [[ 4 -gt 0 ]]
+ case "$1" in
+ print_build_logs=y
+ shift
+ [[ 3 -gt 0 ]]
+ case "$1" in
+ flake=.#hetzner-robot
+ shift
+ shift
+ [[ 1 -gt 0 ]]
+ case "$1" in
+ [[ -z '' ]]
+ ssh_connection=root@<IP>
+ shift
+ [[ 0 -gt 0 ]]
+ [[ y == \y ]]
+ nix_options+=("-L")
+ [[ y == \y ]]
+ nix_copy_options+=("--substitute-on-destination")
+ [[ -z '' ]]
+ [[ -z root@<IP> ]]
++ mktemp -d
+ ssh_key_dir=/tmp/tmp.dGZL9rHkIP
+ trap 'rm -rf "$ssh_key_dir"' EXIT
+ mkdir -p /tmp/tmp.dGZL9rHkIP
+ mkdir -p /home/ravloony/.ssh/
+ ssh-keygen -t ed25519 -f /tmp/tmp.dGZL9rHkIP/nixos-anywhere -P '' -C nixos-anywhere
+ [[ -n .#hetzner-robot ]]
+ [[ .#hetzner-robot =~ ^(.*)#([^#"]*)$ ]]
+ flake=.
+ flakeAttr=hetzner-robot
+ [[ -z hetzner-robot ]]
+ [[ n == \n ]]
+ [[ -n '' ]]
++ nix_build '.#nixosConfigurations."hetzner-robot".config.system.build.diskoScript'
++ NIX_SSHOPTS='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/tmp.dGZL9rHkIP/nixos-anywhere '
++ nix build --print-out-paths --no-link --extra-experimental-features 'nix-command flakes' --no-write-lock-file -L '.#nixosConfigurations."hetzner-robot".config.system.build.diskoScript'
+ disko_script=
+ rm -rf /tmp/tmp.dGZL9rHkIP
```

It looks like the output of the nix-build command is not being put in the disko_script variable, but I don't see why the script then exits.
I would be very grateful for some advice here, or a bugfix if it is a bug.

It's probably worth mentioning that I'm using bash and nix on Ubuntu, not nixos. Possibly a factor here.

**Comment by Mic92** [comment]
I think you are missing an actual disko configuration. Without configuration there is no `diskoScript` output.
