### ISSUE TITLE
Possible bugs in failure shell hooks

### ISSUE THREAD

**Issue by dpc** [nix-community/nixos-anywhere#322]
```
The operation has completed successfully.
+ partprobe /dev/sda1
/nix/store/msdqx0gn7gag7mg4smm7ww3v7a6invh0-disko: line 43: /nix/store/92k36w5ibc909sr3n6aksqqxbawj530q-parted-3.6/bin/partprobe: Input/output error
+ :
+ udevadm trigger --subsystem-match=block
/nix/store/msdqx0gn7gag7mg4smm7ww3v7a6invh0-disko: line 44: udevadm: command not found
+ rm -rf /tmp/tmp.33mwAApB03
/nix/store/msdqx0gn7gag7mg4smm7ww3v7a6invh0-disko: line 1: rm: command not found
```

I've ran this with `/dev/sda1` instead of `/dev/sda` and it rightfully failed, but it seems to expose the fact that `udevadm` and `rm` need to be referred by the full path as they might not be in the PATH?

Please excuse if I'm wrong, just trying to be helpful.

**Comment by Mic92** [comment]
The disko script doesn't copy any dependencies in its closure. This is so that low-memory machines don't go out of memory because large closures are uploaded. We therefore don't use absolute paths. The kexec image that we provide should provide all these tools.
