### ISSUE TITLE
How can I troubleshoot when kexec hangs on install?

### ISSUE THREAD

**Issue by madorian** [nix-community/nixos-anywhere#337]
I'm trying to nixos-anywhere onto an m92p and it just freeze after kexec. 

I found another brave soul who [experience the same.](https://discourse.nixos.org/t/kexec-hangs-on-install/40969/2) 

After kexec, there is no more contact. 

How on earth would I go about troubleshooting that?;)

**Comment by madorian** [comment]
I've now tried on a Lenovo T520 and I get the same. 

This used to work before. I got to ask, is it supposed to be working, as of now;)

**Comment by Mic92** [comment]
Discussion was moved to https://github.com/nix-community/nixos-anywhere/issues/289
