### ISSUE TITLE
Cannot SSH into Hetzner bare metal after install

### ISSUE THREAD

**Issue by szethh** [nix-community/nixos-anywhere#346]
I am trying to bootstrap a heztner bare metal server with nixos. The installation process seems to go fine (no errors), but after the machine reboots it becomes unreachable (pings, ssh, etc).

I then have to setup the rescue system and send a ctrl+alt+del to get access to it again.

My config is here https://github.com/szethh/nixie/blob/main/hosts/htz/default.nix

The command I use to run it is:
`nix -v run github:nix-community/nixos-anywhere -- --debug -L root@ip --flake .#htz --build-on-remote`

I need to use `build-on-remote` since I am on macos.

The machine is an Intel, with 2 sata HDDs, if that matters.

I am quite new to this project, to disko, and nixos in general, so I might be overlooking something obvious here 😅

**Comment by johanot** [comment]
Same here. Tried everything today:

- downgrading nixos-anywhere
- downgrading kexec-image
- downgrading nixpkgs

nothing works. Seems almost like some network issue at Hetzner, but that's just weird.

The only strange thing I could see while debugging the kexec-installer was the it seems like e1000e negotiated 10Mb/s full-duplex.

**Comment by szethh** [comment]
I tried the suggestions from @Mic92 on #110 but no luck.

Maybe something changed recently from hetzner's side?

In any case do let me know if you find a fix, this is quite puzzling

**Comment by johanot** [comment]
I've been compiling kernels most of the day, but alas.

The only breakthrough I had is that everything works with non-intel nics, i.e. Realtek (which is generally in the AMD-series).

It looks like e1000e (intel nics) fails to negotiate link properly after kexec. After reboot everything is fine. It only happens in the kexec environment. I also tried unloading and loading the driver again inside the kexec env - no luck.

**Comment by johanot** [comment]
@szethh The final test I wanted to make for today actually made it work! (for me at least)

`--kexec-extra-flags "--no-ifdown"`

**Comment by szethh** [comment]
did you many any other changes to your config?

i tried that flag but i still can't ssh or ping the machine in any way... these are the last logs i get before it reboots and goes dark:

```sh
+ kexecSyscallFlags=--kexec-syscall-auto
+ sh -c '/root/kexec/kexec/kexec' --load '/root/kexec/kexec/bzImage'   --kexec-syscall-auto   --no-ifdown   --initrd='/root/kexec/kexec/initrd' --no-checks   --command-line 'init=/nix/store/w5967zp4vrgi8hhsyzb6xv6pv02182j2-nixos-system-nixos-installer-24.05pre-git/init console=tty0 console=ttyS0,115200 root=fstab loglevel=4'
machine will boot into nixos in 6s...
+ echo machine will boot into nixos in 6s...
+ test -e /dev/kmsg
+ exec
+ timeout_ssh_ -- exit 0
+ timeout 10 ssh -i /tmp/tmp.D2PJmr8Y50/nixos-anywhere -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@ip -- exit 0
Warning: Permanently added 'ip' (ED25519) to the list of known hosts.
+ ssh_connection=root@ip
+ ssh_ -o ConnectTimeout=10 -- exit 0
+ ssh -t -i /tmp/tmp.D2PJmr8Y50/nixos-anywhere -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@ip -o ConnectTimeout=10 -- exit 0
ssh: connect to host ip port 22: Operation timed out
+ sleep 5
...
# repeated ssh attempts, all timed out
```

**Comment by johanot** [comment]
**Update:**

- AMD (Realtek) just works every time I try - no issues.
- Still don't know why I got a sudden success on Intel, haven't been able to reproduce since.

I spend an entire day debugging. Tried unloading and loading the e1000e driver multiple times, even tried asking the driver to reset the NIC and many other things, but I have limited knowledge - and time, especially when the virtual consolve (KVM) is difficult to get for larger periods in Hetzner. I also asked Hetzner directly for help, but they said it smells like software, which they don't provide support for.

So instead of fighting the kexec+intel+kexec problem even more, I went with a modified version of nixos-anywhere: https://github.com/johanot/nixos-anywhere/commit/2c804da6062055d52fab08340de76a1ae3578bf1 that uses the rescue system itself as partitioning/install environment, instead of kexec. It's not very far from just re-writing my own install-script from scratch, but maybe with the right cleanup and parameterize, it can become a PR to nixos-anywhere some day. - e.g `--no-kexec` + `--prepare-installer-script` :shrug:

**Comment by Mic92** [comment]
I once use this script on hetzner on an intel machine that did not support kexec: https://github.com/nix-community/nixos-anywhere/issues/136
It modifies their rescue system to pretend to be a nixos installer.

**Comment by Mic92** [comment]
Apparently there is also hardware (usually PCI devices) that doesn't support kexec because it cannot be restarted. I believe the Linux port on ARM macbooks for example these issue.

**Comment by johanot** [comment]
@Mic92 Thanks! The funny thing here is that I'm 100% certain that my 4-5 intel machines at Hetzner worked with kexec without issues like 3-4 weeks ago... So I wonder what changed...  Trying different kernels doesn't help, so I lean towards either new firmware or changed switch configuration at Hetzner...  But yeah, we can workaround it for sure.

**Comment by jozuas** [comment]
Alas https://github.com/johanot/nixos-anywhere/commit/2c804da did not work for me with a Hetzner EX101 😢

**Comment by Mic92** [comment]
@jozuas nixos-anywhere never worked for me on EX101 and I also had serious issue with this hardware very reproducible resetting afterwards under load (a nix build is enough). I have a few other people that also report EX101 crashing, I would not recommend this hardware at all.

**Comment by Mic92** [comment]
I used this script in the hetzner installer instead: https://github.com/nix-community/nixos-anywhere/issues/136 to fake a NixOS installer.

**Comment by jozuas** [comment]
@Mic92 In your experience is AX102 a better choice then hardware-wise? It's in a similar price range to EX101.

**Comment by onnimonni** [comment]
I'm able to use the kexec in rescue mode and setting up disks with disko inside kexec works perfectly even with ZFS partitions but when I reboot the new install it doesn't come up. (eg it doesn't respond to ping or netcat).

Are there ways to boot again to the rescue and see the failed boot logs by mounting certain disk?

I think I also have the intel network card:
```
$ lspci | grep -E -i --color 'network|ethernet|wireless|wi-fi'
07:00.0 Ethernet controller: Intel Corporation I210 Gigabit Network Connection (rev 03)
```

Would someone else who has been able to deploy to hetzner with same network device want to share their nix configuration for me?

**Comment by jozuas** [comment]
@onnimonni:

My output:
```
[nix-shell:/opt/terrapin-app]$ lspci | grep -E -i --color 'network|ethernet|wireless|wi-fi'
29:00.0 Ethernet controller: Intel Corporation I210 Gigabit Network Connection (rev 03)
```

I recommend to follow https://github.com/nix-community/nixos-anywhere/issues/346#issuecomment-2348316544 to generate the right `networking.nix` file. As for hardware, you can install `nix` and run `nixos-generate-config` in the Hetzner rescue system to generate `hardware-configuration.nix` and ensure that you are configuring the right kernel modules.

**Comment by Mic92** [comment]
If you have issues after installation, you can order the KVM console. I usually order it for 3 hours as time passes quickly. This should allow you to figure out if you got partitioning wrong or messed up the boot loader. Notice that new machines in Hetzner use UEFI rather than BIOS. In srvos we have profiles for several hetzner machine setups: https://github.com/nix-community/srvos

We also deploy hetzner machines in nix-community: https://github.com/nix-community/infra if you are looking for an end-to-end example

**Comment by onnimonni** [comment]
Thank you both for great examples. I'm pretty new in this community and it's amazing how helpful everyone has been so far ❤️.

I really like how easy it's to follow the build0{1-X} servers and you have great comments like this one:
https://github.com/nix-community/infra/blob/master/modules/nixos/disko-zfs.nix#L5-L10

I'm quite a beginner and I'm not sure if I will be able to figure out my problems inside KVM so I will still try again by replicating the setups you have.

The `flake.nix` inside the https://github.com/nix-community/infra repo is pretty complicated for me what would be the minimal `myHost.nix` to use in the example setup to just get logged into Hetzner bare metal server? I think I will just use the same `disko-zfs.nix` setup as you have.

```nix
{
  description = "My machines flakes";
  inputs = {
    srvos.url = "github:nix-community/srvos";
    # Use the version of nixpkgs that has been tested to work with SrvOS
    # Alternatively we also support the latest nixos release and unstable
    nixpkgs.follows = "srvos/nixpkgs";
  };
  outputs = { self, nixpkgs, srvos }: {
    nixosConfigurations.myHost = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        # This machine is a server
        srvos.nixosModules.server
        # Deployed on the AMD Hetzner hardware
        srvos.nixosModules.hardware-hetzner-amd
        # Configured with extra terminfos
        srvos.nixosModules.mixins-terminfo
        # And designed to run the GitHub Actions runners
        srvos.nixosModules.roles-github-actions-runner
        # Finally add your configuration here
        ./myHost.nix
      ];
    };
  };
}
```

And did you originally deploy these using the nixos-anywhere or in other way?

I will be very happy to contribute to the docs after getting bare minimal setup working 🙇

**Comment by Mic92** [comment]
Nothing actionable in this pull request for nixos-anywhere. Hope the user-provided examples help.
