### ISSUE TITLE
Automatically run fstrim somewhere in the process

### ISSUE THREAD

**Issue by Bert-Proesmans** [nix-community/nixos-anywhere#353]
I've been using older/unused samsung NVMe drives to repurpose as nixos boot drives for labo machines. 

So far I have had consistent issues with booting after first install on those drives. The symptoms are; 
1. partitioning = ok
2. installing = ok
3. booting = NOK -> magic codes on disk are incorrect and cause partition/filesystem/mounting errors -> boot failures due to missing block devices and filesystems

Also these issues consistently dissapear after keeping the system on for multiple hours and kludging with free space commands. Performing exactly the same installation a second time (very easy, very nice, thanks to nixos + nixos-anywhere) results in a working system. The nixos config in question was never incorrect.

As for the reason I'm not 100% certain**, I know at a high level that SSD's need to garbage collect and perform wear leveling, but none of these administrative operations match incorrect reads from backing store. These could be real block defects, just that the controller wasn't aware or possibly forgot.

In any case, nudging the nvme to start checking the backing store might give quicker convergence to expected behaviour. Executing an fstrim after mounting empty filesystems, or fstrim before partitioning anything, or an nvme namespace reformat before partitioning, are possibilities to that goal.

** The disks in question are never defect, according to smartctl, with quoted percentage used below 10% and available spare above 85%. The disks otherwise respond fine to management queries.

**Comment by sedlund** [comment]
this project does not format or partition, that is done with disko.

you don't mention specifics as far as hardware or software or configuration.

i assume you are kexec'ing and it is possible your hardware does not like the state it is in for whatever reason.

i suggest booting from the [community installer](https://github.com/nix-community/nixos-images?tab=readme-ov-file#iso-installer-images) which nixos-anywhere/disko will connect to install from. 

that will give you an idea of if your hardware does not like the kexec.   as  you've said, the 'performing ... installation a second time' works - i am reading from this that the system is booted into nixos and you reinstall with nixos-anyhwere- which does not use kexec.

some hardware will never support kexec.

**Comment by Bert-Proesmans** [comment]
hey, thanks for responding! this ticket was not created to sollicit support and I was purposefully vague about hardware details.
You're right that disko is the better place for this suggestion, they trigger the actual fsyncs.

to be more clear about the possibility of kexec being a (partial) cause to the described symptoms;
* Happens when booting the minimal install iso, and also customized minimal install iso (with my ssh key injected)
* Happens when booting from USB on bare metal (never had issues in vm + iso boot)
* Happens on samsung and intel nvme's (I wrongly assumed my pile of second-hand nvme's was all produced by samsung)
* Happens with entirely different nixos configurations; different flakes, different input channels, different configs

'performing ... installation a second time' is in reality the most naïve interpretation; from my development host I execute nixos-anywhere to deploy my nixos configuration over ssh to a host booted on the nixos minimal install iso. rebooting again into the install iso environment when post-install-boot **hangs** and executing the exact same nixos-anywhere command again.

yes this is weird, hence this ticket to document. i'm experienced enough to ad-hoc fix this, no problem.
