### ISSUE TITLE
Can't install to ipv6 only server because github.com is not usable

### ISSUE THREAD

**Issue by onnimonni** [nix-community/nixos-anywhere#370]
I just tried to buy ipv6 only server from hetzner and to install nixos into the server. I realized that github can't be through ipv6 since it doesn't have `AAAA` dns record.

I'm using `--build-on-remote` because my Macbook throw this error:

```
error: a 'x86_64-linux' with features {} is required to build '/nix/store/...-disko.drv', but I am a 'aarch64-darwin' with features {apple-virt, benchmark, big-parallel, nixos-test}
```

Could there be a way to somehow circumvent this?

**Comment by sedlund** [comment]
https://github.com/nix-community/nixos-anywhere/blob/ef708ac46d83dbf3871efc25befb9c13bd5702a8/docs/howtos/ipv6.md

**Comment by onnimonni** [comment]
Thanks for a fast feedback and sorry I didn't notice this on my own!
