### ISSUE TITLE
Clean up known_hosts after done

### ISSUE THREAD

**Issue by dpc** [nix-community/nixos-anywhere#406]
Seems like an extra step that always needs to be taken care of manually, while an automated `ssh-keygen -R hostname` would just free user from it.

**Comment by sedlund** [comment]
it already outputs known hosts to /dev/null when calling ssh

https://github.com/nix-community/nixos-anywhere/blob/main/src/nixos-anywhere.sh#L322-L335

**Comment by dpc** [comment]
Huh... Then I'm not sure if it was because I was using a slightly older version that didn't have it, or was it because I ran `ssh-copy-id` before (is it even required?).

**Comment by sedlund** [comment]
> or was it because I ran ssh-copy-id before (is it even required?).

Probably that.  No, not required.  If you have a password it will ask, and set up it's temporary keys

**Comment by sedlund** [comment]
what are you envisioning from this feature request?

**Comment by dpc** [comment]
At the end of the day... `ssh-keygen -R hostname` being called at the end of successful `nixos-anywhere`, I guess.

**Comment by phaer** [comment]
But nixos-anywhere isn't supposed to create a new entry in your known_hosts file, as @sedlund pointed out above. If it does, that would most probably be a bug.

As it stands, I believe you could just call ssh-keygen -R in the same layer where you are calling ssh-copy-id, creating the entry in the first place.

**Comment by dpc** [comment]
OK then.
