### ISSUE TITLE
feat: How to connect with different user after reboot?

### ISSUE THREAD

**Issue by gabyx** [nix-community/nixos-anywhere#409]
I have VM that has a user `ubuntu`.

 I can run `nixos-anywhere --flake ... 11.11.11.11`  (which actually works on engine.switch.ch which is really great). The `~/.ssh/config` is:

```ini
Host 11.11.11.11
    IdentityFile ~/.ssh/vm
    IdentitiesOnly yes
    User ubuntu
```

However once it reboots -> I can no longer connect because the user changed to `root` =). It works if I in the meantime change the `User ubuntu` to `User root`.

Is there a way to somehow trick `nixos-anywhere` to use `root` after install or some other ssh options?

**Comment by gabyx** [comment]
Or even maybe `nixos-anywhere` could provide an option: `--post-kexec-ssh-user` or even `--post-kexec-ssh-hostname` where the later gives the opportunity to use `--post-kexec-ssh-hostname afterinstall` with an `~/.ssh/config` as;

```ini
Host 11.11.11.11
    IdentityFile ~/.ssh/vm
    IdentitiesOnly yes
    User ubuntu

Host afterinstall
    IdentityFile ~/.ssh/vm
    IdentitiesOnly yes
    User root
```

**Comment by sedlund** [comment]
It should kexec onto the new kernel (this is not a reboot) and nixos-anywhere will reconnect to the machine using generated ssh keys from prior to kexec and install nixos.  is this not happening?

your nixosConfiguration flake should have configured the user and ssh key (if that is your method to connect) to use after reboot.

by after reboot am I correct to think that NixOS is installed at this point?  If that is the case nixos-anywheres job is [complete](https://github.com/nix-community/nixos-anywhere/blob/main/docs/quickstart.md#finished).

**Comment by gabyx** [comment]
> your nixosConfiguration flake should have configured the user and ssh key (if that is your method to connect) to use after reboot.
Jeah: My ssh config is the same as  https://github.com/nix-community/nixos-anywhere-examples/blob/main/configuration.nix#L26

First I do `nixos-anywhere --flake ubuntu@host` and then the installation after `kexec` fails to reconnect, I can leave it trying to reconnect -> and change `User` to `root` in the `.ssh/config` and then it suddenly works and I see all nix store paths getting copied and the install finished successfully =)

**Comment by sedlund** [comment]
please provide the full logs with `--debug` enabled along with the command you are running.

it should be trying to reconnect with the user provided to install as and using the generated key that it installed.

you can try to debug why ssh is not allowing login by logging in yourself after kexec and looking at the ssh logs.  

the nixos-anywhere key will be inserted into `~ubuntu/.ssh/authorized_keys` via `ssh-copy-id` the private key on the installer machine will be in `/tmp/tmp.SOMEWHERE` you will see when you run it with `--debug`.

**Comment by sedlund** [comment]
you should not be having this

>     IdentitiesOnly yes

**Comment by gabyx** [comment]
@sedlund : Ah thanks a lot!

**Comment by gabyx** [comment]
See #411. Thanks.
