### ISSUE TITLE
System not rebooting if sudo is present and --extra-files is used

### ISSUE THREAD

**Issue by madjam002** [nix-community/nixos-anywhere#431]
When using --extra-files, I've noticed that the system is not rebooting automatically after installation.

I think the installation is failing at the point where the extra files are copied across

https://github.com/nix-community/nixos-anywhere/blob/9ba099b2ead073e0801b863c880be03a981f2dd1/src/nixos-anywhere.sh#L580

Is `maybeSudo` supposed to be used here even in the kexec environment? As it's logging that the command cannot be found in the installer kexec environment.

Uninstalling sudo before running nixos-anywhere works fine.

**Comment by Zempashi** [comment]
Perfect timing, I was encountering the issue as well right now. Workaround also works for me as I log in root before kexec.

**Comment by thenbe** [comment]
When using terraform all-in-one, this error is "flaky" - as in it occurs roughly 50% the time. I'm not sure why the error only occurs sometimes when I run `terraform apply`, and does not occur every time I run `terraform apply`.
